BUILD_DIR=build
RNO_G_INSTALL_DIR?=/rno-g/
PREFIX?=$(RNO_G_INSTALL_DIR)
CFLAGS=-Og -fPIC -Wall -Wextra -g -std=gnu11 -I$(RNO_G_INSTALL_DIR)/include -fanalyzer
BINDIR=bin

ON_DIDAQ?=no

#check if on revn board
ifneq (,$(shell grep RevN /proc/device-tree/model 2> /dev/null))
$(info We are on the DiDAQ)
ON_DIDAQ=yes
endif

LDFLAGS=-L$(RNO_G_INSTALL_DIR)/lib
LIBS=-lz -pthread -lrno-g -lrno-g-cal -lconfig -lm -lsystemd

INCLUDES=src/ice-config.h src/ice-buf.h src/ice-common.h

ifeq ($(ON_DIDAQ),yes)
    CFLAGS += -DON_DIDAQ
	LIBS += -ldidaq -lrno-g-didaq -lgpios
else
	LIBS += -lradiant -lflower
endif

SERVO_DEBUG?=no
ifeq ($(SERVO_DEBUG),yes)
	CFLAGS += -DSERVO_DEBUG
endif

.PHONY: all clean install uninstall setup cfg-update cfg-install cppcheck service-install cfg-round-trip-check FORCE

OBJS:=$(addprefix $(BUILD_DIR)/, ice-config.o ice-buf.o ice-common.o ice-version.o)

BINS:=$(addprefix $(BINDIR)/, rno-g-acq make-default-rno-g-config check-rno-g-config update-rno-g-config rno-g-find-config)



STATION_NUMBER=$(shell if [ -f /STATION_ID ] ; then printf "%03d" `cat /STATION_ID`; fi )
$(info STATION_NUMBER=${STATION_NUMBER})

all: $(OBJS) $(BINS)

$(BINDIR)/update-rno-g-config:  $(BINDIR)/check-rno-g-config
	ln -f $< $@

$(BINDIR)/%: src/%.c $(INCLUDES) $(OBJS) Makefile | $(BINDIR)
	@echo Compiling $@
	@cc -o $@ $(CFLAGS) $< $(OBJS) $(LDFLAGS) $(LIBS)

$(BUILD_DIR)/%.o: src/%.c $(INCLUDES) | $(BUILD_DIR)
	@echo Compiling $@
	@cc -c -o $@ $(CFLAGS) $<

# Auto-generated git hash. FORCE makes it always considered out of date so the
# hash is re-checked on every build, but the file (and hence its mtime) is only
# replaced when the hash actually changed. Only build targets pull this in, so
# e.g. cfg-install never writes into src/.
FORCE:

src/ice-version.c: FORCE
	@/bin/echo -e "/*This file is auto-generated by the Makefile!*/\n#include \"ice-version.h\"\n\nconst char *  get_ice_software_git_hash() { return \"$$(git describe --always --dirty --match 'NOT A TAG')\";}" > $@.tmp
	@if diff -q $@.tmp $@ >/dev/null 2>&1; then rm $@.tmp; else mv $@.tmp $@; fi


$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

$(BINDIR):
	@mkdir -p $(BINDIR)


clean:
	rm -rf $(BUILD_DIR)
	rm -rf $(BINDIR)

setup:
	mkdir -p $(PREFIX)/run
	chown rno-g:rno-g $(PREFIX)/run
	mkdir -p $(PREFIX)/var
	chown rno-g:rno-g $(PREFIX)/var
	mkdir -p $(PREFIX)/cfg
	chown rno-g:rno-g $(PREFIX)/cfg
	mkdir -p $(PREFIX)/bin
	chown rno-g:rno-g $(PREFIX)/bin
	mkdir -p /data/daq
	chown rno-g:rno-g /data/daq
	mkdir -p /data/timing
	chown rno-g:rno-g /data/timing
	mkdir -p /data/power
	chown rno-g:rno-g /data/power
	touch $(PREFIX)/var/calib_channel.state
	chown rno-g:rno-g $(PREFIX)/var/calib_channel.state



install: $(BINS) setup
	install $(BINS) $(PREFIX)/bin
	install scripts/rno-g-* $(PREFIX)/bin
	install scripts/calibration/rno-g-apply-calib scripts/calibration/apply_acq_overrides.py $(PREFIX)/bin
	install -m 644 scripts/calibration/overrides.json $(PREFIX)/cfg
	install cfg/acq.cfg $(PREFIX)/cfg/acq.cfg.default

cfg-update: $(BINDIR)/update-rno-g-config
	@ echo "Updating acq configs"
	@$(BINDIR)/make-default-rno-g-config acq cfg/acq.cfg
	@ for i in cfg/acq*.cfg ; do echo $$i ; $(BINDIR)/update-rno-g-config acq $$i ; done

cfg-install:
	@ echo "Installing configuration..."
	@ if [ -f cfg/acq-${STATION_NUMBER}.cfg ] ; \
	then \
		echo "Using station-specific file cfg/acq-${STATION_NUMBER}.cfg" ; install cfg/acq-${STATION_NUMBER}.cfg $(PREFIX)/cfg/acq.cfg ;\
	else \
		echo "Using default cfg/acq.cfg" ; install cfg/acq.cfg $(PREFIX)/cfg/acq.cfg ; \
	fi
	@mkdir -p ${PREFIX}/cfg/acq.cfg.once

cfg-round-trip-check:
	@echo checking config round trip for acq.cfg
	@$(BINDIR)/check-rno-g-config acq cfg/acq.cfg | diff cfg/acq.cfg -



cppcheck:
	cppcheck --enable=portability --enable=performance --enable=information  src

polkit-install:
	install -d /etc/polkit-1/rules.d
	install polkit/rno-g.rules /etc/polkit-1/rules.d/10-rno-g.rules

service-install: polkit-install
	install systemd/*.service systemd/*.timer systemd/*.target /etc/systemd/system
	systemctl daemon-reload
