#! /bin/sh

# This script only copies data in `aux/*` and `cfg/*`. It does not delet any files.

STN=$(cat /STATION_ID | tr -d '\n')

# exclude everyting in a run directory except for aux and cfg
excludes='--exclude "header/" --exclude "waveforms/" --exclude "daqstatus/" --exclude "pedestals.dat.gz" --exclude "bias_scan.dat.gz"'

while true;
do
  rsync -avh $excludes /data/daq/ 10.1.0.1:/data/ingress/station$STN/

  # only delete if rsync succeeds correctly
  if [ $? -ne 0 ] ; then
    continue ;
  fi

  sleep 120;
done
