#! /bin/sh

# This script only copies data in `aux/*` and `cfg/*`. It does not delet any files.

STN=$(cat /STATION_ID | tr -d '\n')

while true;
do
  sleep 60;
  rsync -avh --exclude "*" --include 'aux/*' --include 'cfg/*' /data/daq/ 10.1.0.1:/data/ingress/station$STN/

  # only delete if rsync succeeds correctly
  if [ $? -ne 0 ] ; then
    continue ;
  fi


done
